using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace API.Utility
{
    public class Static
    {        
        public static string Declaration = @" I hereby state that I have no objection in authenticating myself with Aadhaar based authentication system and consent to providing my Aadhaar number, Biometric and/or One Time Pin (OTP) data for Aadhaar based authentication for the purposes of availing of the Digital Signature Certificate from Capricorn Identity Services Pvt. Ltd.. I understand that the Biometrics and/or OTP I provide for authentication shall be used only for authenticating my identity through the Aadhaar Authentication system, for obtaining my e-KYC through Aadhaar e-KYC service and for the issuance of Digital Signature Certificate (DSC) for this specific transaction and for no other purposes. For the creation of DSC, I understand that the options that I have chosen are the ones that shall be populated in the DSC generated by the CA and I provide my consent for the same. 
                                                               
I understand that Capricorn Identity Services Pvt. Ltd. shall ensure security and confidentiality of my personal identity data provided for the purpose of Aadhaar based authentication.
       
I also have read and understood Capricorn CA CPS and agree on terms and usage for my Digital Signature Certificate.
";

    }
}